### ISSUE TITLE
Bug: not able to convert

### ISSUE THREAD

**Issue by dubey-suraj** [mratul07/ReactJs-LearnWhatMatters#2]
when I click on button convert. It's not working

![image](https://github.com/mratul07/ReactJs-LearnWhatMatters/assets/93868837/76758910-abb9-4261-837c-2f3d3087bec9)

**Comment by dubey-suraj** [comment]
It was silly mistake. I missed backticks (` `) while api call.

**Comment by vikramnagwal** [comment]
"I was working on it." 👍

**Comment by dubey-suraj** [comment]
> "I was working on it." 👍

just a syntactical issue. I missed backticks in fetch(). So I closed it. Look at the code
![image](https://github.com/mratul07/ReactJs-LearnWhatMatters/assets/93868837/6520a5cd-b67f-4d68-ab50-de4cb6d40b97)
